export const socialItem = [
    {
        id: 1,
        col: 'hsl(208, 92%, 53%)',
        icon: '../../images/icon-facebook.svg',
        name: '@nathanf',        
        stat: '1987',
        cat: 'FOLLOWERS',
        varia: '../../images/icon-up.svg', 
        typeVaria: 'inc', 
        num: '12', 
    },
    {
        id: 2,
        col: 'hsl(203, 89%, 53%)',
        icon: '../../images/icon-twitter.svg',
        name: '@nathanf',        
        stat: '1044',
        cat: 'FOLLOWERS',
        varia: '../../images/icon-up.svg',
        typeVaria: 'inc',
        num: '99',   
    },
    {
        id: 3,
        col: 'linear-gradient(45deg, rgb(253,196,104), rgb(223, 73, 150))',
        icon: '../../images/icon-instagram.svg',
        name: '@realnathanf',        
        stat: '11k',
        cat: 'FOLLOWERS',
        varia: '../../images/icon-up.svg',  
        typeVaria: 'inc',
        num: '1099', 
    },
    {
        id: 4,
        col: 'hsl(348, 97%, 39%)',
        icon: '../../images/icon-youtube.svg',
        name: 'Nathan F.',            
        stat: '8239',
        cat: 'SUBSCRIBERS',
        varia: '../../images/icon-down.svg', 
        typeVaria: 'dec',
        num: '144',  
    }
];

export const overviewItem = [
    {
        id: 1,
        icon: '../../images/icon-facebook.svg',
        title: 'Page Views',        
        num: '87', 
        perc: '3%',
        iconVaria: '../../images/icon-up.svg',
        typeVaria: 'inc',
    },
    {
        id: 2,
        icon: '../../images/icon-facebook.svg',
        title: 'Likes',        
        num: '52', 
        perc: '2%',
        iconVaria: '../../images/icon-down.svg',
        typeVaria: 'dec',
    },
    {
        id: 3,
        icon: '../../images/icon-instagram.svg',
        title: 'Likes',        
        num: '5462', 
        perc: '2257%',
        iconVaria: '../../images/icon-up.svg',
        typeVaria: 'inc',
    },
    {
        id: 4,
        icon: '../../images/icon-instagram.svg',
        title: 'Profile Views',        
        num: '52k', 
        perc: '1375%',
        iconVaria: '../../images/icon-up.svg',
        typeVaria: 'inc',
    },
    {
        id: 5,
        icon: '../../images/icon-twitter.svg',
        title: 'Retweets',        
        num: '117', 
        perc: '303%',
        iconVaria: '../../images/icon-up.svg',
        typeVaria: 'inc',
    },
    {
        id: 6,
        icon: '../../images/icon-twitter.svg',
        title: 'Likes',        
        num: '507', 
        perc: '553%',
        iconVaria: '../../images/icon-up.svg',
        typeVaria: 'inc',
    },
    {
        id: 7,
        icon: '../../images/icon-youtube.svg',
        title: 'Likes',        
        num: '107', 
        perc: '19%',
        iconVaria: '../../images/icon-down.svg',
        typeVaria: 'dec',
    },
    {
        id: 8,
        icon: '../../images/icon-youtube.svg',
        title: 'Total Views',        
        num: '1407', 
        perc: '12%',
        iconVaria: '../../images/icon-down.svg',
        typeVaria: 'dec',
    },
    
];